name: snap_local
description: A social media application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.6+50

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  android_id: ^0.4.0

  animated_bottom_navigation_bar: ^1.3.3
  package_info_plus: ^8.3.0
  #better_player: ^0.0.84
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.0.1
  collection: ^1.18.0
  confetti: ^0.8.0
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  designer:
    path: ./packages/designer
  device_info_plus: ^11.4.0
  device_preview: ^1.2.0
  dio: ^5.4.3+1
  dotted_border: ^3.0.1
  dotted_line: ^3.2.2
  #easy_image_viewer: ^1.4.1
  easy_localization: ^3.0.6
  equatable: ^2.0.5
  fast_rsa: ^3.6.1
  feather_icons: ^1.2.0
  #ffmpeg_kit_flutter: ^6.0.3
  #ffmpeg_kit_flutter_full: ^6.0.3
  #ffmpeg_kit_flutter_new: ^1.6.1
  #ffmpeg_kit_flutter_minimal: ^6.0.4
  file_picker: ^10.1.9
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.1
  flutter_carousel_widget: ^3.0.0
  flutter_circular_text: ^0.3.1
  flutter_downloader: ^1.11.7
  flutter_facebook_auth: ^7.0.1
  flutter_image_compress: ^2.2.0
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^19.2.1
  flutter_rating_stars: ^1.1.0
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.5
  geolocator: ^14.0.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  google_maps_cluster_manager_2: ^3.2.0
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hydrated_bloc: ^9.1.5
  image: ^4.1.7
  image_picker: ^1.1.2
  internet_handler:
    path: ./packages/internet_handler
  intl: ^0.20.2
  mockito: ^5.4.4
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  responsive_framework: ^1.4.0
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^11.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  simple_gradient_text: ^1.3.0
  sm_camera:
    git:
      url: https://github.com/swayamshreemohanty/sm_camera
      ref: 0.2.2
  smooth_page_indicator: ^1.1.0
  stroke_text: ^1.0.0
  syncfusion_flutter_charts: ^29.2.5
  syncfusion_flutter_core: ^29.2.5
  syncfusion_flutter_pdfviewer: ^29.2.5
  syncfusion_flutter_sliders: ^29.2.5
  synchronized: ^3.1.0+1
  text_scroll: ^0.2.0
  timer_count_down: ^2.2.2
  translator: ^1.0.0
  tutorial_coach_mark: ^1.2.11
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  version: ^3.0.2
  video_compress: ^3.1.3
  #video_player: ^2.9.5
  visibility_detector: ^0.4.0+2
  volume_controller: ^3.4.0
  timeago: ^3.6.1
  emoji_picker_flutter: ^4.3.0
  geohash_plus: ^1.1.1
  video_thumbnail: ^0.5.6
  flutter_native_video_trimmer: ^1.1.9
  #cached_video_player_plus: ^3.0.3
  showcaseview: ^4.0.1
  video_player: ^2.10.0
  #flick_video_player: ^0.9.0
  #better_player_plus: ^1.0.8
  #flutter_vlc_player: ^7.4.1
  #media_kit: ^1.2.0
  #media_kit_video: ^1.2.0
  #media_kit_libs_video: ^1.0.5 # Native video dependencies.


dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/reaction/gifs/
    - assets/images/page_header/
    - assets/images/common/
    - assets/images/splash/
    - assets/images/bottom_bar/
    - assets/images/bottom_bar/introduction/
    - assets/images/home/
    - assets/images/bottom_bar/news/
    - assets/images/event/
    - assets/images/business/
    - assets/images/ratings_star/
    - assets/images/post/
    - assets/images/market/
    - assets/images/post/visibility/
    - assets/images/map/
    - assets/images/map/map_view_marker/
    - assets/images/profile/
    - assets/images/settings_menu/
    - assets/images/profile/connection/
    - assets/images/profile/privacy/
    - assets/images/static_assets/
    - assets/images/authentication/png/
    - assets/images/authentication/svg/
    - assets/images/bottom_bar/more/
    - assets/images/empty_data_placeholder/
    - assets/images/new_images/
    - assets/images/chat/
    - assets/images/bottom_bar/more/jobs/
    - assets/images/news/
    - assets/local_images/
    - assets/tutorials/
    #sounds
    - assets/sounds/

    #ca
    - assets/ca/

    #keys
    - assets/keys/rsa_keys/

    # #paypal logo
    # - assets/images/paypal_logo.png

    # #amazon logo
    # - assets/images/amazon_logo.png
